// Resolves slugs against worksheets-manifest.json.
// Static JSON import → Vercel's file tracer bundles the manifest automatically.
// The manifest is generated by `scripts/build-worksheets-manifest.mjs`
// (run as the Vercel buildCommand, and locally before `vercel dev`).
import { fileURLToPath } from "node:url";
import { dirname, join, isAbsolute } from "node:path";
import manifest from "../../worksheets-manifest.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = join(__dirname, "..", "..");

// resolve(slug) -> { slug, title, niche, pdfPath (absolute) } | null
export function resolve(slug) {
  if (!slug || typeof slug !== "string") return null;
  const entry = manifest.worksheets?.[slug];
  if (!entry) return null;
  const pdfPath = isAbsolute(entry.pdfPath) ? entry.pdfPath : join(REPO, entry.pdfPath);
  return { slug, title: entry.title, niche: entry.niche, pdfPath };
}

export function listSlugs() {
  return Object.keys(manifest.worksheets ?? {});
}
