#!/usr/bin/env python3
"""
Convert worksheet JSON → Canva design prompt.
Input: worksheet JSON generated by generate_worksheet_outline.py
Output: Canva AI prompt ready to paste into Canva interface.

Usage:
  python3 scripts/generate_canva_worksheet_prompt.py --input content/worksheets/[slug]_worksheet.json
"""

import json
import sys
from pathlib import Path
import argparse


def load_worksheet(filepath: str) -> dict:
    """Load worksheet JSON."""
    with open(filepath, "r", encoding="utf-8") as f:
        return json.load(f)


def load_canva_templates(template_file: str = "prompts/worksheet_canva_prompts.md") -> dict:
    """Parse worksheet_canva_prompts.md into structured templates."""
    templates = {}
    content = Path(template_file).read_text(encoding="utf-8")

    # Split by h2 headers (looking for "## Data Science" and "## Life & Self-Dev")
    sections = content.split("## ")[1:]

    for section in sections:
        lines = section.split("\n", 1)
        title = lines[0].strip()
        body = lines[1] if len(lines) > 1 else ""

        # Extract prompt between triple backticks
        if "```" in body:
            prompt_start = body.find("```") + 3
            prompt_end = body.find("```", prompt_start)
            if prompt_end > prompt_start:
                prompt = body[prompt_start:prompt_end].strip()
                templates[title.lower()] = prompt

    return templates


def build_canva_prompt(worksheet: dict, template: str) -> str:
    """Merge worksheet data into Canva template."""
    # Substitute worksheet title
    prompt = template.replace("{worksheet_title}", worksheet.get("title", "Worksheet"))
    prompt = prompt.replace("{niche}", worksheet.get("niche", ""))

    # Build sections from worksheet
    if "sections" in worksheet:
        sections_text = ""
        for i, section in enumerate(worksheet["sections"], 1):
            sections_text += f"\n{i}. {section.get('title', '')}\n"

            if "prompts" in section:
                for p in section["prompts"]:
                    sections_text += f"   - {p}\n"
            elif "prompt" in section:
                prompt_val = section['prompt']
                # Handle both string and list prompts
                if isinstance(prompt_val, list):
                    for p in prompt_val:
                        sections_text += f"   - {p}\n"
                else:
                    sections_text += f"   {prompt_val}\n"
            elif "template" in section:
                sections_text += f"   {section['template']}\n"

        # Replace "Sections:" line and everything after with new sections
        if "Sections:" in prompt:
            sections_start = prompt.find("Sections:")
            prompt = prompt[:sections_start] + f"Sections:{sections_text}\n\n"
        else:
            prompt += f"\n\nSections:{sections_text}"

    return prompt


def main():
    parser = argparse.ArgumentParser(description="Generate Canva prompt from worksheet JSON")
    parser.add_argument("--input", "-i", required=True, help="Path to worksheet JSON")
    parser.add_argument("--template-file", "-t", default="prompts/worksheet_canva_prompts.md",
                        help="Path to Canva templates markdown")
    parser.add_argument("--output", "-o", help="Save prompt to file (optional; auto-generated from slug if omitted)")

    args = parser.parse_args()

    # Load worksheet
    worksheet = load_worksheet(args.input)
    niche = worksheet.get("niche", "").replace("_", " ").title()

    # Load Canva templates
    templates = load_canva_templates(args.template_file)

    # Pick template by niche (flexible matching)
    template = None
    worksheet_niche = worksheet.get("niche", "").lower()

    for template_key, template_content in templates.items():
        template_key_lower = template_key.lower()
        if "data_science" in worksheet_niche and "data science" in template_key_lower:
            template = template_content
            break
        elif "life" in worksheet_niche and "life" in template_key_lower:
            template = template_content
            break

    if not template:
        print(f"Available templates: {list(templates.keys())}")
        print(f"Error: No Canva template found for niche '{worksheet_niche}'")
        sys.exit(1)
    prompt = build_canva_prompt(worksheet, template)

    # Output
    print("\n" + "=" * 80)
    print("CANVA DESIGN PROMPT")
    print("=" * 80)
    print(prompt)
    print("=" * 80)

    output_path = args.output
    if not output_path:
        slug = Path(args.input).stem.replace("_worksheet", "")
        output_path = f"content/prompts/{slug}_worksheet_prompt.txt"

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(prompt, encoding="utf-8")
    print(f"\n✓ Saved to: {output_path}")

    print("\n📋 NEXT STEPS:")
    print("1. Copy the prompt above")
    print("2. Go to Canva.com → Create Design → Custom Size (A4)")
    print("3. Paste prompt into Canva AI design generator (or manually design using the structure)")
    print("4. Export as PDF")
    print("5. Upload PDF to ConvertKit landing page as free download")


if __name__ == "__main__":
    main()
