#!/bin/bash
# YouTube Shorts upload commands — generated by load_posts.py
# Run on Friday after recording.

# 2026-05-21_data_science_tech_complete-python-course-2026-beginner-to-advance-tutorial-110
python3 scripts/upload_youtube.py --shorts --slug "2026-05-21_data_science_tech_complete-python-course-2026-beginner-to-advance-tutorial-110" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-21_data_science_tech_complete-python-course-2026-beginner-to-advance-tutorial-110_reel.mp4" --category 22

# 2026-05-21_life_self_dev_how-i-turned-my-habits-into-an-engine-to-get-me-to-my-goals
python3 scripts/upload_youtube.py --shorts --slug "2026-05-21_life_self_dev_how-i-turned-my-habits-into-an-engine-to-get-me-to-my-goals" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-21_life_self_dev_how-i-turned-my-habits-into-an-engine-to-get-me-to-my-goals_reel.mp4" --category 22

# 2026-05-21_poetry_quotes_when-dreams-speak-of-love
python3 scripts/upload_youtube.py --shorts --slug "2026-05-21_poetry_quotes_when-dreams-speak-of-love" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-21_poetry_quotes_when-dreams-speak-of-love_reel.mp4" --category 22

# 2026-05-25_data_science_tech_python-for-data-science-tutorial-210
python3 scripts/upload_youtube.py --shorts --slug "2026-05-25_data_science_tech_python-for-data-science-tutorial-210" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-25_data_science_tech_python-for-data-science-tutorial-210_reel.mp4" --category 22

# 2026-05-26_life_self_dev_mental-health-openness-and-breaking-stigmas
python3 scripts/upload_youtube.py --shorts --slug "2026-05-26_life_self_dev_mental-health-openness-and-breaking-stigmas" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-26_life_self_dev_mental-health-openness-and-breaking-stigmas_reel.mp4" --category 22

# 2026-05-27_poetry_quotes_intoxicated-senses
python3 scripts/upload_youtube.py --shorts --slug "2026-05-27_poetry_quotes_intoxicated-senses" --channel "Breath of Data Science" --video "assets/video/edited/2026-05-27_poetry_quotes_intoxicated-senses_reel.mp4" --category 22

# 2026-06-01_data_science_tech_python-for-data-science-tutorial-310
python3 scripts/upload_youtube.py --shorts --slug "2026-06-01_data_science_tech_python-for-data-science-tutorial-310" --channel "Breath of Data Science" --video "assets/video/edited/2026-06-01_data_science_tech_python-for-data-science-tutorial-310_reel.mp4" --category 22

# 2026-06-01_life_self_dev_the-cost-of-carrying-things-nobody-sees
python3 scripts/upload_youtube.py --shorts --slug "2026-06-01_life_self_dev_the-cost-of-carrying-things-nobody-sees" --channel "Breath of Data Science" --video "assets/video/edited/2026-06-01_life_self_dev_the-cost-of-carrying-things-nobody-sees_reel.mp4" --category 22

# 2026-06-01_poetry_quotes_looking-at-the-world-through-a-reflective-lens
python3 scripts/upload_youtube.py --shorts --slug "2026-06-01_poetry_quotes_looking-at-the-world-through-a-reflective-lens" --channel "Breath of Data Science" --video "assets/video/edited/2026-06-01_poetry_quotes_looking-at-the-world-through-a-reflective-lens_reel.mp4" --category 22
